### ISSUE TITLE
好像不能输入多个值

### ISSUE THREAD

**Issue by HuParry** [yzyyz1387/nonebot_plugin_code#3]
当代码要输入多个数时，就有bug了，不知道有没有解决办法。

**Comment by HuParry** [comment]
![Uploading DDC2000B-12DA-4AF5-BA47-D8576E1546D2.png…]()

**Comment by HuParry** [comment]
![Uploading 187B356D-7AD2-48A5-991D-5E76FD47CED9.png…]()

**Comment by HuParry** [comment]
> 当代码要输入多个数时，就有bug了，不知道有没有解决办法。
![Uploading CCA10374-5CDE-4486-84A4-1E882F9D23B7.png…]()

**Comment by yzyyz1387** [comment]
在忙，将在年后处理
